ReversiRestApi/ReversiMvcApp/Controllers/SpelersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReversiMvcApp.Data;
using ReversiMvcApp.Models;

namespace ReversiMvcApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SpelersController : Controller
    {
        private readonly reversiDbContext _context;

        public SpelersController(reversiDbContext context)
        {
            _context = context;
        }

        // GET: Spelers  
        public async Task<IActionResult> Index()
        {
            return View(await _context.Spelers.ToListAsync());
        }

        // GET: Spelers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spelers = await _context.Spelers
                .FirstOrDefaultAsync(m => m.Guid == id);
            if (spelers == null)
            {
                return NotFound();
            }

            return View(spelers);
        }

        // GET: Spelers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Spelers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Guid,Name,AantalGewonnen,AantalVerloren,AantalGelijk")] Spelers spelers)
        {
            if (ModelState.IsValid)
            {
                _context.Add(spelers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(spelers);
        }

        // GET: Spelers/Edit/5 
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spelers = await _context.Spelers.FindAsync(id);
            if (spelers == null)
            {
                return NotFound();
            }
            return View(spelers);
        }

        // POST: Spelers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Guid,Name,AantalGewonnen,AantalVerloren,AantalGelijk")] Spelers spelers)
        {
            if (id != spelers.Guid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(spelers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpelersExists(spelers.Guid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(spelers);
        }

        // GET: Spelers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var spelers = await _context.Spelers
                .FirstOrDefaultAsync(m => m.Guid == id);
            if (spelers == null)
            {
                return NotFound();
            }

            return View(spelers);
        }

        // POST: Spelers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var spelers = await _context.Spelers.FindAsync(id);
            _context.Spelers.Remove(spelers);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SpelersExists(string id)
        {
            return _context.Spelers.Any(e => e.Guid == id);
        }
    }
}

ReversiRestApi/ReversiMvcApp/Controllers/SpellenController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ReversiMvcApp.Models;
using ReversiRestApi.Data;
using ReversiRestApi.Model;
using System.Diagnostics;
using System.Security.Claims;

namespace ReversiMvcApp.Controllers
{
    [Authorize]
    public class SpellenController : Controller
    {
        private UserManager<IdentityUser> _userManager;
        public SpellenController(UserManager<IdentityUser> userManager) { 
            _userManager = userManager;
        }
        
        // GET: SpellenControllers
        public ActionResult Index()
        {
            ViewBag.userMangager = _userManager;
            return View("index",APIReversi.GetWaitingSpel().Result);
        }

        public ActionResult SpellenSpeler()
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            return View("spellenSpeler", APIReversi.GetSpellenSpeler(currentUserID).Result);

        }

        public ActionResult SpelerStats()
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;

            return View("stats", APIReversi.GetSpellenSpeler(currentUserID).Result);

        }

        // GET: SpellenControllers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SpellenControllers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            ClaimsPrincipal currentUser = this.User;
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            Debug.WriteLine(collection["Omschrijving"]);
            Debug.WriteLine(currentUserID);

            APIReversi.PostCreateSpel(currentUserID, collection["Omschrijving"]);
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult Spel(string id) {
            Spel s = APIReversi.GetSpel(id).Result;
            ViewData["speler1"] = "Me";
            ViewData["speler2"] = _userManager.FindByIdAsync(s.Speler2Token).Result.UserName;
            return View("spel", s);
        }

        [HttpGet]
        public ActionResult Join(string id) {
            ClaimsPrincipal currentUser = this.User;
            Spel s = APIReversi.GetSpel(id).Result;
            ViewData["speler1"] = _userManager.FindByIdAsync(s.Speler1Token).Result.UserName;
            ViewData["speler2"] = "Me";
            var currentUserID = currentUser.FindFirst(ClaimTypes.NameIdentifier).Value;
            APIReversi.PostJoin(id,currentUserID).Wait();
            

        return View("spel", APIReversi.GetSpel(id).Result); 
        }
    }
}

ReversiRestApi/ReversiMvcApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Components.Authorization
@using ReversiMvcApp.Helper


@{
    string authorizedUsers = "";

    string token = LatestGame.GetLatestSpel().Token;


}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReversiMvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReversiMvcApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/animation.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/mobile.css" asp-append-version="true" />
    

    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style=" width: 10vw;"><img src="https://pbs.twimg.com/media/ECNgTPeWwAAbVF1.jpg" width=100% height=100%/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spellen" asp-action="index">zoeken</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spellen" asp-action="SpelerStats">Stats</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Spellen" asp-action="SpellenSpeler">Mijn spellen</a>
                        </li>
                        @if (this.User != null)
                        {
                            @if (this.User.Claims.Any(s => s.Value == ClaimHelper.Admin))
                            {
                                
                                <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="index"> Admin Panel</a></li>
                                <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Spelers" asp-action="index">Spelers</a></li>
                            }
                            @if (this.User.Claims.Any(s => s.Value == ClaimHelper.Moderator))
                            {
                                <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Moderator" asp-action="index"> Moderator Panel</a></li>
                            }
                        }
                       

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div id="feedback" class="alert alert-success fade-in" role="alert" style="display: none;">
        <div id="feedback-content" class="">
            <button name="feedback-close" class="feedback-widget-close">X</button>
            <p class="feedback-widget-text">woop :(</p>
                <a asp-area="" asp-controller="Spellen" asp-action="Spel" asp-route-id="@token" class="feedback-widget-accept wiggle">
                    <button id="feedback-accept" name="feedback-accept" >Accept</button>
                </a>
            <button name="feedback-reject" class="feedback-widget-reject">Reject</button>
        </div>
</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script src="~/js/LocalLogging.js"></script>
    <script src="~/js/FeedbackWidget.js"></script>
    <script>
           $(function() {
        console.log( "ready!" );
    });

    function notify(){
    var x= $.ajax({
            url:'https://' + location.host + '/redirect/GetSpel/@token',
            

            }).done(function(){
            console.log(x.responseJSON);
            if(x.responseJSON.speler2Token != null){  
                FeedbackWidget.show("feedback","succes","Join game");
            }

            setTimeout(notify,1000);
        
        });
    }
    notify();
    //FeedbackWidget.show("succes","woop :(");
    </script>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ReversiMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>